In [2]:
import pandas as pd
import numpy as np

In [19]:
print("1.", np.identity(5))
print("2.", np.diag([1,2,3,4]))


cb = np.zeros((8,8), dtype='int32')
cb[::2,::2] = 1
cb[1::2,1::2] = 1
cb

1. [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
2. [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
3. [[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [29]:
ar = np.array(np.arange(1,11))
print("bytes occupied in the memory", ar.nbytes)

bytes occupied in the memory 40


In [55]:
ar = np.array([[200,210,209],[213,0,214],[214,215,217]])
print(ar)

ar_flat = ar.flatten()
ar[1,1] = np.mean(ar_flat)
print("mean filling", ar)
ar[1,1] = np.median(ar_flat)
print("median filling", ar)

# looks like mean approximation is spoiling the original value, 
# either we have to reduce the divisor by -1 or 
# median seems to provide closer value in our case.

[[200 210 209]
 [213   0 214]
 [214 215 217]]
mean filling [[200 210 209]
 [213 188 214]
 [214 215 217]]
median filling [[200 210 209]
 [213 213 214]
 [214 215 217]]


In [56]:
# create pd series of class size 50
marks = pd.Series(np.random.randint(100,size=50))
print ("filter the marks >50", marks[marks>50])
print ("filter the marks >70", marks[marks>70])
print ("filter the marks >90", marks[marks>80])

filter the marks >50 0     87
3     63
5     70
6     77
7     88
8     97
10    67
13    65
19    55
20    70
21    70
23    97
26    57
28    88
30    52
31    93
32    58
33    63
34    88
36    63
37    83
38    90
40    98
42    70
44    86
45    89
46    94
49    98
dtype: int32
filter the marks >70 0     87
6     77
7     88
8     97
23    97
28    88
31    93
34    88
37    83
38    90
40    98
44    86
45    89
46    94
49    98
dtype: int32
filter the marks >90 0     87
7     88
8     97
23    97
28    88
31    93
34    88
37    83
38    90
40    98
44    86
45    89
46    94
49    98
dtype: int32


In [65]:
name=np.array(['kevin','john','hari'])
age=np.array([23,21,22])
gender=np.array(['m','m','f'])
state=np.array(['TN','KL','KN'])
cgpa=np.array([9,8,7])

df = pd.DataFrame({'name':name,'age':age,'gender':gender,'state':state,'cgpa':cgpa})
df

name  age gender state  cgpa
0  kevin   23      m    TN     9
1   john   21      m    KL     8
2   hari   22      f    KN     7

In [80]:
print("#1.Filter the age")
print(df['age'])
print("\n\n#2.filter age,cgpa")
print(df[['age', 'cgpa']])
print("\n\n#3.Filter age>22")
print(df['age'][df['age']>22])
print("\n\n#4.names starts with j")
print(df['name'][df['name'].str.startswith('j')])
print("\n\n#5.names contains 'n'")
print(df['name'][df['name'].str.contains('j')])


#1.Filter the age
0    23
1    21
2    22
Name: age, dtype: int32


#2.filter age,cgpa
   age  cgpa
0   23     9
1   21     8
2   22     7


#3.Filter age>22
0    23
Name: age, dtype: int32


#4.names starts with j
1    john
Name: name, dtype: object


#5.names contains 'n'
1    john
Name: name, dtype: object


In [89]:
dfr1=pd.DataFrame({'Id':[1,2,3,5,9],
                    'Col1':[1,2,3,4,5],
                     'col2':[6,7,8,9,10],
                      'col4':['apple','orange','banana','strawberry','rasberry']})
dfr2=pd.DataFrame({'Id':[1,1,3,5],
                    'ColA':[8,9,10,11],
                     'colB':[12,13,15,17],
                      'col4':['apple','orange','banana','kiwi']})
print("left join:")
print(dfr1.join(dfr2, lsuffix='fr1', rsuffix='fr2', how='left'))
print("\nright join:")
print(dfr1.join(dfr2, lsuffix='fr1', rsuffix='fr2', how='right'))
print("\ninner join:")
print(dfr1.join(dfr2, lsuffix='fr1', rsuffix='fr2', how='inner'))

left join:
   Idfr1  Col1  col2     col4fr1  Idfr2  ColA  colB col4fr2
0      1     1     6       apple    1.0   8.0  12.0   apple
1      2     2     7      orange    1.0   9.0  13.0  orange
2      3     3     8      banana    3.0  10.0  15.0  banana
3      5     4     9  strawberry    5.0  11.0  17.0    kiwi
4      9     5    10    rasberry    NaN   NaN   NaN     NaN

right join:
   Idfr1  Col1  col2     col4fr1  Idfr2  ColA  colB col4fr2
0      1     1     6       apple      1     8    12   apple
1      2     2     7      orange      1     9    13  orange
2      3     3     8      banana      3    10    15  banana
3      5     4     9  strawberry      5    11    17    kiwi

inner join:
   Idfr1  Col1  col2     col4fr1  Idfr2  ColA  colB col4fr2
0      1     1     6       apple      1     8    12   apple
1      2     2     7      orange      1     9    13  orange
2      3     3     8      banana      3    10    15  banana
3      5     4     9  strawberry      5    11    17    kiwi


In [94]:
#1.define sigmoid function
sig_fun = lambda x: 1/(1 + np.exp(-x))
#2.create the np array
ar = np.array([2,5,6])
#3.Apply the function to the array
sig_fun(ar)

array([0.88079708, 0.99330715, 0.99752738])